# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\26811\Desktop\PAXING\PyQt-main\System_paxing.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1826, 1026)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1600, 900))
        MainWindow.setMaximumSize(QtCore.QSize(3840, 2160))
        font = QtGui.QFont()
        font.setPointSize(14)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setMinimumSize(QtCore.QSize(1600, 900))
        self.centralWidget.setMaximumSize(QtCore.QSize(3840, 2160))
        self.centralWidget.setStyleSheet("background-color: rgb(105, 105, 105);")
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(8, 0, 8, 30)
        self.verticalLayout_5.setSpacing(8)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupConfig = QtWidgets.QWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupConfig.sizePolicy().hasHeightForWidth())
        self.groupConfig.setSizePolicy(sizePolicy)
        self.groupConfig.setMinimumSize(QtCore.QSize(0, 65))
        self.groupConfig.setStyleSheet("background-color:#d3d3d3;\n"
"font: 22pt \"Adobe 黑体 Std R\";")
        self.groupConfig.setObjectName("groupConfig")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupConfig)
        self.horizontalLayout_2.setContentsMargins(80, 0, 80, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.groupConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.verticalLayout_4.addWidget(self.groupConfig)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupTarget = QtWidgets.QGroupBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupTarget.sizePolicy().hasHeightForWidth())
        self.groupTarget.setSizePolicy(sizePolicy)
        self.groupTarget.setMinimumSize(QtCore.QSize(850, 0))
        self.groupTarget.setMaximumSize(QtCore.QSize(900, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupTarget.setFont(font)
        self.groupTarget.setStyleSheet("")
        self.groupTarget.setTitle("")
        self.groupTarget.setObjectName("groupTarget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupTarget)
        self.verticalLayout_2.setContentsMargins(-1, 3, -1, 3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.SingleMachine = QtWidgets.QGroupBox(self.groupTarget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SingleMachine.sizePolicy().hasHeightForWidth())
        self.SingleMachine.setSizePolicy(sizePolicy)
        self.SingleMachine.setMinimumSize(QtCore.QSize(0, 120))
        self.SingleMachine.setStyleSheet("font: 15pt \"Adobe 黑体 Std R\";\n"
"border-color: rgb(249, 249, 249);\n"
"border: 3px solid #f9f9f9;      /* 边框粗细+颜色 */\n"
"border-radius: 8px;         /* 圆角半径 */\n"
"margin-top: 1ex;\n"
"color:white\n"
"")
        self.SingleMachine.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.SingleMachine.setFlat(False)
        self.SingleMachine.setCheckable(False)
        self.SingleMachine.setObjectName("SingleMachine")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.SingleMachine)
        self.verticalLayout_9.setContentsMargins(-1, 5, -1, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.widget = QtWidgets.QWidget(self.SingleMachine)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 80))
        self.widget.setStyleSheet("border-color: rgb(173, 178, 181);\n"
"background-color:#d3d3d3;\n"
"border-radius: 0px; \n"
"color:black;\n"
"font: 14pt \"Adobe 黑体 Std R\";\n"
"\n"
"")
        self.widget.setObjectName("widget")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_10.setContentsMargins(-1, 11, -1, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 60))
        self.widget_2.setStyleSheet("border:none;\n"
"\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.connect_led = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connect_led.sizePolicy().hasHeightForWidth())
        self.connect_led.setSizePolicy(sizePolicy)
        self.connect_led.setMinimumSize(QtCore.QSize(40, 40))
        self.connect_led.setStyleSheet("background-color: red;\n"
"border-radius: 20px; \n"
"border: 1px solid gray;\n"
"margin-top: 0px;\n"
"")
        self.connect_led.setText("")
        self.connect_led.setObjectName("connect_led")
        self.horizontalLayout_3.addWidget(self.connect_led)
        self.button_connect = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_connect.sizePolicy().hasHeightForWidth())
        self.button_connect.setSizePolicy(sizePolicy)
        self.button_connect.setMinimumSize(QtCore.QSize(70, 0))
        self.button_connect.setStyleSheet("background-color: #f4f4f4;\n"
"color: black;\n"
"   \n"
"padding: 5px 10px;\n"
"\n"
"border-left:0px;\n"
"border-top:0px;\n"
" border-right: 2px solid #a3a3a3;  /* 右边边框 */\n"
"    border-bottom: 2px solid #a3a3a3; /* 下边边框 */\n"
"margin-top: 0px;")
        self.button_connect.setObjectName("button_connect")
        self.horizontalLayout_3.addWidget(self.button_connect)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.button_motor = QtWidgets.QPushButton(self.widget_2)
        self.button_motor.setStyleSheet("background-color: #f4f4f4;\n"
"color: black;\n"
"   \n"
"padding: 5px 10px;\n"
"\n"
"border-left:0px;\n"
"border-top:0px;\n"
" border-right: 2px solid #a3a3a3;  /* 右边边框 */\n"
"    border-bottom: 2px solid #a3a3a3; /* 下边边框 */\n"
"margin-top: 0px;")
        self.button_motor.setObjectName("button_motor")
        self.horizontalLayout_3.addWidget(self.button_motor)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)

        # 创建一个水平容器，模拟原按钮的外观（宽度240，带边框）
        switch_container = QtWidgets.QWidget(self.widget_2)
        switch_container.setMinimumSize(QtCore.QSize(270, 50))
        switch_container.setStyleSheet(
        "background-color: #f4f4f4;\n"
        "border-right: 0px solid #a3a3a3;\n"
        "border-bottom: 0px solid #a3a3a3;"
        )

        # 容器内的水平布局
        inner_layout = QtWidgets.QHBoxLayout(switch_container)
        inner_layout.setContentsMargins(5, 0, 5, 0)  # 模拟原 padding
        inner_layout.setSpacing(8)

        # 1. 下拉框：供电选择
        self.check_switch = QtWidgets.QComboBox(switch_container)
        self.check_switch.addItems(["A侧供电", "B侧供电"])
        self.check_switch.setStyleSheet(
        "QComboBox { padding: 4px; background: white; border: 1px solid #ccc; }"
        "QComboBox::drop-down { width: 20px; }"
        )

        # 2. 按钮：开启/切换（保留原变量名）
        self.button_switch = QtWidgets.QPushButton("开启/切换", switch_container)
        self.button_switch.setStyleSheet(
        "QPushButton {"
        "   background-color: #e0e0e0;"
        "   border: 1px solid #a3a3a3;"
        "   padding: 4px 8px;"
        "}"
        "QPushButton:hover { background-color: #d0d0d0; }"
        )

        # 添加到内部布局
        inner_layout.addWidget(self.check_switch)
        inner_layout.addWidget(self.button_switch)

        # 将整个组合添加到原布局（替换原来的 button_switch）
        self.horizontalLayout_3.addWidget(switch_container)

        spacerItem2 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)

        # 创建一个容器 widget 模拟按钮外观
        button_container = QtWidgets.QWidget(self.widget_2)
        button_container.setMinimumSize(QtCore.QSize(240, 50))  # 高度需增加以容纳文字
        button_container.setStyleSheet(
        "background-color: #f4f4f4;\n"
        "border-right: 2px solid #a3a3a3;\n"
        "border-bottom: 2px solid #a3a3a3;"
        )
        container_layout = QtWidgets.QHBoxLayout(button_container)
        container_layout.setContentsMargins(0, 0, 0, 0)  # 上下留点空间
        container_layout.setSpacing(0)  # LED 之间的间距

        led_size = 20

        # 添加 7 个 LED（编号 3 到 9）
        for i in range(3, 10):
                # 为每个 LED + 文字创建一个垂直容器
                led_widget = QtWidgets.QWidget(button_container)
                led_layout = QtWidgets.QVBoxLayout(led_widget)
                led_layout.setContentsMargins(0, 5, 0, 0)
                led_layout.setSpacing(0)
                # LED 指示灯
                led = QtWidgets.QLabel(led_widget)
                led.setFixedSize(led_size, led_size)
                led.setStyleSheet("""
                        background-color: red;
                        border-radius: 10px; 
                        border: 1px solid gray;
                        margin-top: 0px;
                """)
                led.setText("")

                # 文字标签
                label = QtWidgets.QLabel(str(i), led_widget)
                label.setAlignment(QtCore.Qt.AlignCenter)
                label.setStyleSheet("font-size: 15px; color: black; padding-bottom: 5px;")  # 可调整字体

                # 添加到垂直布局
                led_layout.addWidget(led, alignment=QtCore.Qt.AlignCenter)
                led_layout.addWidget(label, alignment=QtCore.Qt.AlignCenter)

                # 绑定到 self.output_led3 ~ self.output_led9
                setattr(self, f"output_led{i}", led)

                # 将整个小部件加入主水平布局
                container_layout.addWidget(led_widget)

        # 将容器添加到原布局
        self.horizontalLayout_3.addWidget(button_container)

        self.verticalLayout_10.addWidget(self.widget_2)
        self.verticalLayout_9.addWidget(self.widget)
        self.verticalLayout_2.addWidget(self.SingleMachine)
        self.SingleMachine_2 = QtWidgets.QGroupBox(self.groupTarget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SingleMachine_2.sizePolicy().hasHeightForWidth())
        self.SingleMachine_2.setSizePolicy(sizePolicy)
        self.SingleMachine_2.setMinimumSize(QtCore.QSize(0, 185))
        self.SingleMachine_2.setStyleSheet("font: 15pt \"Adobe 黑体 Std R\";\n"
"border-color: rgb(249, 249, 249);\n"
"border: 3px solid #f9f9f9;      /* 边框粗细+颜色 */\n"
"border-radius: 8px;         /* 圆角半径 */\n"
"margin-top: 1ex;\n"
"color:white\n"
"")
        self.SingleMachine_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.SingleMachine_2.setFlat(False)
        self.SingleMachine_2.setCheckable(False)
        self.SingleMachine_2.setObjectName("SingleMachine_2")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.SingleMachine_2)
        self.verticalLayout_13.setContentsMargins(-1, 5, -1, 5)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.widget_3 = QtWidgets.QWidget(self.SingleMachine_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setMinimumSize(QtCore.QSize(776, 145))
        self.widget_3.setStyleSheet("border-color: rgb(173, 178, 181);\n"
"background-color:#d3d3d3;\n"
"border-radius: 0px; \n"
"color:black;\n"
"font: 14pt \"Adobe 黑体 Std R\";\n"
"\n"
"")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_14.setContentsMargins(-1, 11, -1, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.widget_15 = QtWidgets.QWidget(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_15.sizePolicy().hasHeightForWidth())
        self.widget_15.setSizePolicy(sizePolicy)
        self.widget_15.setMinimumSize(QtCore.QSize(0, 45))
        self.widget_15.setStyleSheet("border:none;margin-top: 0px;\n"
"\n"
"")
        self.widget_15.setObjectName("widget_15")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.widget_15)
        self.horizontalLayout_15.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.start_led = QtWidgets.QLabel(self.widget_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_led.sizePolicy().hasHeightForWidth())
        self.start_led.setSizePolicy(sizePolicy)
        self.start_led.setMinimumSize(QtCore.QSize(40, 40))
        self.start_led.setStyleSheet("background-color: red;\n"
"border-radius: 20px; \n"
"border: 1px solid gray;\n"
"margin-top: 0px;\n"
"")
        self.start_led.setText("")
        self.start_led.setObjectName("start_led")
        self.horizontalLayout_15.addWidget(self.start_led)
        self.box_motor = QtWidgets.QComboBox(self.widget_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_motor.sizePolicy().hasHeightForWidth())
        self.box_motor.setSizePolicy(sizePolicy)
        self.box_motor.setMinimumSize(QtCore.QSize(150, 0))
        self.box_motor.setStyleSheet("background-color: #f9f9f9;\n"
"padding: 5px 10px;\n"
"border:none;\n"
"margin-top: 0px;")
        self.box_motor.setObjectName("box_motor")
        self.horizontalLayout_15.addWidget(self.box_motor)
        spacerItem3 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem3)
        self.button_start = QtWidgets.QPushButton(self.widget_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_start.sizePolicy().hasHeightForWidth())
        self.button_start.setSizePolicy(sizePolicy)
        self.button_start.setMinimumSize(QtCore.QSize(70, 0))
        self.button_start.setStyleSheet("background-color: #f4f4f4;\n"
"color: black;\n"
"   \n"
"padding: 5px 10px;\n"
"\n"
"border-left:0px;\n"
"border-top:0px;\n"
" border-right: 2px solid #a3a3a3;  /* 右边边框 */\n"
"    border-bottom: 2px solid #a3a3a3; /* 下边边框 */\n"
"margin-top: 0px;")
        self.button_start.setObjectName("button_start")
        self.horizontalLayout_15.addWidget(self.button_start)
        spacerItem4 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem4)
        self.button_forward = QtWidgets.QPushButton(self.widget_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_forward.sizePolicy().hasHeightForWidth())
        self.button_forward.setSizePolicy(sizePolicy)
        self.button_forward.setMinimumSize(QtCore.QSize(70, 0))
        self.button_forward.setStyleSheet("background-color: #f4f4f4;\n"
"color: black;\n"
"   \n"
"padding: 5px 10px;\n"
"\n"
"border-left:0px;\n"
"border-top:0px;\n"
" border-right: 2px solid #a3a3a3;  /* 右边边框 */\n"
"    border-bottom: 2px solid #a3a3a3; /* 下边边框 */\n"
"margin-top: 0px;")
        self.button_forward.setObjectName("button_forward")
        self.horizontalLayout_15.addWidget(self.button_forward)
        spacerItem5 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem5)
        self.button_reverse = QtWidgets.QPushButton(self.widget_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_reverse.sizePolicy().hasHeightForWidth())
        self.button_reverse.setSizePolicy(sizePolicy)
        self.button_reverse.setMinimumSize(QtCore.QSize(70, 0))
        self.button_reverse.setStyleSheet("background-color: #f4f4f4;\n"
"color: black;\n"
"   \n"
"padding: 5px 10px;\n"
"\n"
"border-left:0px;\n"
"border-top:0px;\n"
" border-right: 2px solid #a3a3a3;  /* 右边边框 */\n"
"    border-bottom: 2px solid #a3a3a3; /* 下边边框 */\n"
"margin-top: 0px;")
        self.button_reverse.setObjectName("button_reverse")
        self.horizontalLayout_15.addWidget(self.button_reverse)
        spacerItem6 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem6)
        self.label_43 = QtWidgets.QLabel(self.widget_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_43.sizePolicy().hasHeightForWidth())
        self.label_43.setSizePolicy(sizePolicy)
        self.label_43.setMinimumSize(QtCore.QSize(60, 0))
        self.label_43.setStyleSheet("margin-top: 0px;")
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_15.addWidget(self.label_43)
        self.p_edit = QtWidgets.QLineEdit(self.widget_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p_edit.sizePolicy().hasHeightForWidth())
        self.p_edit.setSizePolicy(sizePolicy)
        self.p_edit.setMinimumSize(QtCore.QSize(200, 0))
        self.p_edit.setStyleSheet("background-color: #f9f9f9;\n"
"padding: 5px 10px;\n"
"border:none;\n"
"margin-top: 0px;")
        self.p_edit.setObjectName("p_edit")
        self.horizontalLayout_15.addWidget(self.p_edit)
        self.verticalLayout_14.addWidget(self.widget_15)
        self.widget_16 = QtWidgets.QWidget(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_16.sizePolicy().hasHeightForWidth())
        self.widget_16.setSizePolicy(sizePolicy)
        self.widget_16.setMinimumSize(QtCore.QSize(0, 45))
        self.widget_16.setStyleSheet("border:none;margin-top: 0px;")
        self.widget_16.setObjectName("widget_16")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.widget_16)
        self.horizontalLayout_16.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem7 = QtWidgets.QSpacerItem(130, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem7)
        self.button_stop = QtWidgets.QPushButton(self.widget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_stop.sizePolicy().hasHeightForWidth())
        self.button_stop.setSizePolicy(sizePolicy)
        self.button_stop.setMinimumSize(QtCore.QSize(70, 0))
        self.button_stop.setStyleSheet("background-color: #f4f4f4;\n"
"color: black;\n"
"   \n"
"padding: 5px 10px;\n"
"\n"
"border-left:0px;\n"
"border-top:0px;\n"
" border-right: 2px solid #a3a3a3;  /* 右边边框 */\n"
"    border-bottom: 2px solid #a3a3a3; /* 下边边框 */\n"
"margin-top: 0px;")
        self.button_stop.setObjectName("button_stop")
        self.horizontalLayout_16.addWidget(self.button_stop)
        spacerItem8 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem8)
        self.button_reset = QtWidgets.QPushButton(self.widget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_reset.sizePolicy().hasHeightForWidth())
        self.button_reset.setSizePolicy(sizePolicy)
        self.button_reset.setMinimumSize(QtCore.QSize(70, 0))
        self.button_reset.setStyleSheet("background-color: #f4f4f4;\n"
"color: black;\n"
"   \n"
"padding: 5px 10px;\n"
"\n"
"border-left:0px;\n"
"border-top:0px;\n"
" border-right: 2px solid #a3a3a3;  /* 右边边框 */\n"
"    border-bottom: 2px solid #a3a3a3; /* 下边边框 */\n"
"margin-top: 0px;")
        self.button_reset.setObjectName("button_reset")
        self.horizontalLayout_16.addWidget(self.button_reset)
        spacerItem9 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem9)
        self.button_zero = QtWidgets.QPushButton(self.widget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_zero.sizePolicy().hasHeightForWidth())
        self.button_zero.setSizePolicy(sizePolicy)
        self.button_zero.setMinimumSize(QtCore.QSize(70, 0))
        self.button_zero.setStyleSheet("background-color: #f4f4f4;\n"
"color: black;\n"
"   \n"
"padding: 5px 10px;\n"
"\n"
"border-left:0px;\n"
"border-top:0px;\n"
" border-right: 2px solid #a3a3a3;  /* 右边边框 */\n"
"    border-bottom: 2px solid #a3a3a3; /* 下边边框 */\n"
"margin-top: 0px;")
        self.button_zero.setObjectName("button_zero")
        self.horizontalLayout_16.addWidget(self.button_zero)
        spacerItem10 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem10)
        self.button_move = QtWidgets.QPushButton(self.widget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_move.sizePolicy().hasHeightForWidth())
        self.button_move.setSizePolicy(sizePolicy)
        self.button_move.setMinimumSize(QtCore.QSize(70, 0))
        self.button_move.setStyleSheet("background-color: #f4f4f4;\n"
"color: black;\n"
"   \n"
"padding: 5px 10px;\n"
"\n"
"border-left:0px;\n"
"border-top:0px;\n"
" border-right: 2px solid #a3a3a3;  /* 右边边框 */\n"
"    border-bottom: 2px solid #a3a3a3; /* 下边边框 */\n"
"margin-top: 0px;")
        self.button_move.setObjectName("button_move")
        self.horizontalLayout_16.addWidget(self.button_move)
        spacerItem11 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem11)
        self.label_44 = QtWidgets.QLabel(self.widget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_44.sizePolicy().hasHeightForWidth())
        self.label_44.setSizePolicy(sizePolicy)
        self.label_44.setMinimumSize(QtCore.QSize(60, 0))
        self.label_44.setStyleSheet("border:none;\n"
"margin-top: 0px;\n"
"")
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_16.addWidget(self.label_44)
        self.v_edit = QtWidgets.QLineEdit(self.widget_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.v_edit.sizePolicy().hasHeightForWidth())
        self.v_edit.setSizePolicy(sizePolicy)
        self.v_edit.setMinimumSize(QtCore.QSize(200, 0))
        self.v_edit.setStyleSheet("background-color: #f9f9f9;\n"
"padding: 5px 10px;\n"
"border:none;\n"
"margin-top: 0px;")
        self.v_edit.setObjectName("v_edit")
        self.horizontalLayout_16.addWidget(self.v_edit)
        self.verticalLayout_14.addWidget(self.widget_16)
        self.verticalLayout_13.addWidget(self.widget_3)
        self.verticalLayout_2.addWidget(self.SingleMachine_2)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupTarget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 440))
        self.groupBox_5.setStyleSheet("font: 15pt \"Adobe 黑体 Std R\";\n"
"border-color: rgb(249, 249, 249);\n"
"border: 3px solid #f9f9f9;      /* 边框粗细+颜色 */\n"
"border-radius: 8px;         /* 圆角半径 */\n"
"margin-top: 1ex;\n"
"\n"
"color:white\n"
"")
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_16.setContentsMargins(-1, 11, -1, 3)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.widget_14 = QtWidgets.QWidget(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_14.sizePolicy().hasHeightForWidth())
        self.widget_14.setSizePolicy(sizePolicy)
        self.widget_14.setMinimumSize(QtCore.QSize(0, 260))
        self.widget_14.setStyleSheet("border-color: rgb(173, 178, 181);\n"
"background-color:#d3d3d3;\n"
"border-radius: 0px; \n"
"color:black;\n"
"font: 10pt \"Adobe 黑体 Std R\";\n"
"\n"
"")
        self.widget_14.setObjectName("widget_14")
        #self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_14)
        #self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.widget_22 = QtWidgets.QWidget(self.widget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_22.sizePolicy().hasHeightForWidth())
        self.widget_22.setSizePolicy(sizePolicy)
        self.widget_22.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_22.setStyleSheet("border:none\n"
"")
        # 使用 QVBoxLayout
        self.verticalLayout_201 = QtWidgets.QVBoxLayout(self.widget_22)
        self.verticalLayout_201.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_201.setSpacing(5)
        '''self.button1 = QtWidgets.QPushButton(self.widget_22)
        self.button1.setMinimumSize(QtCore.QSize(120, 0))
        self.button1.setStyleSheet("background-color: #f4f4f4;\n"
"color: black;\n"
"   \n"
"padding: 5px 10px;\n"
"\n"
"border-left:0px;\n"
"border-top:0px;\n"
" border-right: 2px solid #a3a3a3;  /* 右边边框 */\n"
"    border-bottom: 2px solid #a3a3a3; /* 下边边框 */\n"
"margin-top: 0px;")
        self.button1.setObjectName("button1")
        self.horizontalLayout_20.addWidget(self.button1)'''
        #spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        #self.horizontalLayout_20.addItem(spacerItem12)
        '''self.led1 = QtWidgets.QLabel(self.widget_22)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.led1.sizePolicy().hasHeightForWidth())
        self.led1.setSizePolicy(sizePolicy)
        self.led1.setMinimumSize(QtCore.QSize(30, 30))
        self.led1.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"border-radius: 15px; \n"
"border: 1px solid gray;\n"
"margin-top: 0px;\n"
"")
        self.led1.setText("")
        self.led1.setObjectName("led1")
        self.horizontalLayout_20.addWidget(self.led1)'''
        #spacerItem13 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        #self.horizontalLayout_20.addItem(spacerItem13)

        self.button_servo_align1 = QtWidgets.QPushButton(self.widget_22)
        self.button_linear_plan1 = QtWidgets.QPushButton(self.widget_22)
        self.button_close_clampA1 = QtWidgets.QPushButton(self.widget_22)
        self.button_release_clampB1 = QtWidgets.QPushButton(self.widget_22)
        self.button_reverse_linear_1 = QtWidgets.QPushButton(self.widget_22)
        self.button_joint4_reverse_1 = QtWidgets.QPushButton(self.widget_22)
        for i,btn in enumerate([self.button_servo_align1, self.button_linear_plan1, self.button_close_clampA1, self.button_release_clampB1,self.button_reverse_linear_1,self.button_joint4_reverse_1]):
                btn.setStyleSheet("background-color: #f4f4f4;\n"
                "color: black;\n"
                "font: 15pt \"Adobe 黑体 Std R\";\n"
                "   \n"
                #"padding: 5px 10px;\n"
                "\n"
                "border-left:0px;\n"
                "margin-left: 60px;"
                "border-top:0px;\n"
                " border-right: 2px solid #a3a3a3;  /* 右边边框 */\n"
                "    border-bottom: 2px solid #a3a3a3; /* 下边边框 */\n"
                "margin-top: 0px;")
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(btn.sizePolicy().hasHeightForWidth())
                btn.setSizePolicy(sizePolicy)
                btn.setMinimumSize(QtCore.QSize(400, 50))

                # ====== 新增：创建 QLabel 并放入水平布局 ======
                label = QtWidgets.QLabel()
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(label.sizePolicy().hasHeightForWidth())
                label.setSizePolicy(sizePolicy)
                label.setMinimumSize(QtCore.QSize(30, 30))
                label.setStyleSheet("background-color: rgb(255, 0, 0);\n"
        "border-radius: 15px; \n"
        "border: 1px solid gray;\n"
        "margin-top: 0px;\n"
        "")
                label.setText("")
                label.setObjectName(f"led{i+1}")

                h_layout = QtWidgets.QHBoxLayout()
                h_layout.addWidget(btn)
                h_layout.addWidget(label)

                self.verticalLayout_201.addLayout(h_layout)
                self.verticalLayout_201.setStretch(i, 1)
                setattr(self,f"led{i+1}",label)

        self.button_servo_align1.setObjectName("button_servo_align1")
        self.button_linear_plan1.setObjectName("button_linear_plan1")
        self.button_close_clampA1.setObjectName("button_close_clampA1")
        self.button_release_clampB1.setObjectName("button_release_clampB1")
        self.button_reverse_linear_1.setObjectName("button_reverse_linear_1")
        self.button_joint4_reverse_1.setObjectName("button_joint4_reverse_1")


        #self.verticalLayout_12.addWidget(self.widget_22)
        self.widget_23 = QtWidgets.QWidget(self.widget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_23.sizePolicy().hasHeightForWidth())
        self.widget_23.setSizePolicy(sizePolicy)
        self.widget_23.setMinimumSize(QtCore.QSize(0, 45))
        self.widget_23.setStyleSheet("border:none\n"
"")
        self.widget_23.setObjectName("widget_23")
        # 使用 QVBoxLayout
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.widget_23)
        self.verticalLayout_21.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_21.setSpacing(5)
        '''self.button2 = QtWidgets.QPushButton(self.widget_23)
        self.button2.setMinimumSize(QtCore.QSize(120, 0))
        self.button2.setStyleSheet("background-color: #f4f4f4;\n"
"color: black;\n"
"   \n"
"padding: 5px 10px;\n"
"\n"
"border-left:0px;\n"
"border-top:0px;\n"
" border-right: 2px solid #a3a3a3;  /* 右边边框 */\n"
"    border-bottom: 2px solid #a3a3a3; /* 下边边框 */\n"
"margin-top: 0px;")
        self.button2.setObjectName("button2")
        self.horizontalLayout_21.addWidget(self.button2)'''
        #spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        #self.horizontalLayout_21.addItem(spacerItem14)
        '''self.led2 = QtWidgets.QLabel(self.widget_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.led2.sizePolicy().hasHeightForWidth())
        self.led2.setSizePolicy(sizePolicy)
        self.led2.setMinimumSize(QtCore.QSize(30, 30))
        self.led2.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"border-radius: 15px; \n"
"border: 1px solid gray;\n"
"margin-top: 0px;\n"
"")
        self.led2.setText("")
        self.led2.setObjectName("led2")
        self.horizontalLayout_21.addWidget(self.led2)'''
        #spacerItem15 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        #self.horizontalLayout_21.addItem(spacerItem15)

        self.button_servo_align2 = QtWidgets.QPushButton(self.widget_23)
        self.button_linear_plan2 = QtWidgets.QPushButton(self.widget_23)
        self.button_close_clampA2 = QtWidgets.QPushButton(self.widget_23)
        self.button_release_clampB2 = QtWidgets.QPushButton(self.widget_23)
        self.button_reverse_linear_2 = QtWidgets.QPushButton(self.widget_23)
        self.button_joint4_reverse_2 = QtWidgets.QPushButton(self.widget_23)
        for i,btn in enumerate([self.button_servo_align2, self.button_linear_plan2, self.button_close_clampA2, self.button_release_clampB2,self.button_reverse_linear_2,self.button_joint4_reverse_2]):
                btn.setStyleSheet("background-color: #f4f4f4;\n"
                "color: black;\n"
                "font: 15pt \"Adobe 黑体 Std R\";\n"
                "   \n"
                #"padding: 5px 10px;\n"
                "\n"
                "border-left:0px;\n"
                "margin-left: 60px;"
                "border-top:0px;\n"
                " border-right: 2px solid #a3a3a3;  /* 右边边框 */\n"
                "    border-bottom: 2px solid #a3a3a3; /* 下边边框 */\n"
                "margin-top: 0px;")
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(btn.sizePolicy().hasHeightForWidth())
                btn.setSizePolicy(sizePolicy)
                btn.setMinimumSize(QtCore.QSize(400, 50))

                # ====== 新增：创建 QLabel 并放入水平布局 ======
                label = QtWidgets.QLabel()
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(label.sizePolicy().hasHeightForWidth())
                label.setSizePolicy(sizePolicy)
                label.setMinimumSize(QtCore.QSize(30, 30))
                label.setStyleSheet("background-color: rgb(255, 0, 0);\n"
        "border-radius: 15px; \n"
        "border: 1px solid gray;\n"
        "margin-top: 0px;\n"
        "")
                label.setText("")
                label.setObjectName(f"led{i+11}")

                h_layout = QtWidgets.QHBoxLayout()
                h_layout.addWidget(btn)
                h_layout.addWidget(label)

                self.verticalLayout_21.addLayout(h_layout)
                self.verticalLayout_21.setStretch(i, 1)
                setattr(self,f"led{i+11}",label)
                

        self.button_servo_align2.setObjectName("button_servo_align2")
        self.button_linear_plan2.setObjectName("button_linear_plan2")
        self.button_close_clampA2.setObjectName("button_close_clampA2")
        self.button_release_clampB2.setObjectName("button_release_clampB2")
        self.button_reverse_linear_2.setObjectName("button_reverse_linear_2")
        self.button_joint4_reverse_2.setObjectName("button_joint4_reverse_2")

        #self.verticalLayout_12.addWidget(self.widget_23)
        self.widget_24 = QtWidgets.QWidget(self.widget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_24.sizePolicy().hasHeightForWidth())
        self.widget_24.setSizePolicy(sizePolicy)
        self.widget_24.setMinimumSize(QtCore.QSize(0, 45))
        self.widget_24.setStyleSheet("border:none\n"
"")
        self.widget_24.setObjectName("widget_24")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.widget_24)
        self.verticalLayout_22.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_22.setSpacing(5)
        '''self.button3 = QtWidgets.QPushButton(self.widget_24)
        self.button3.setMinimumSize(QtCore.QSize(120, 0))
        self.button3.setStyleSheet("background-color: #f4f4f4;\n"
"color: black;\n"
"   \n"
"padding: 5px 10px;\n"
"\n"
"border-left:0px;\n"
"border-top:0px;\n"
" border-right: 2px solid #a3a3a3;  /* 右边边框 */\n"
"    border-bottom: 2px solid #a3a3a3; /* 下边边框 */\n"
"margin-top: 0px;")
        self.button3.setObjectName("button3")
        self.horizontalLayout_22.addWidget(self.button3)'''
        #spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        #self.horizontalLayout_22.addItem(spacerItem16)
        '''self.led3 = QtWidgets.QLabel(self.widget_24)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.led3.sizePolicy().hasHeightForWidth())
        self.led3.setSizePolicy(sizePolicy)
        self.led3.setMinimumSize(QtCore.QSize(30, 30))
        self.led3.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"border-radius: 15px; \n"
"border: 1px solid gray;\n"
"margin-top: 0px;\n"
"")
        self.led3.setText("")
        self.led3.setObjectName("led3")
        self.horizontalLayout_22.addWidget(self.led3)'''
        #spacerItem17 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        #self.horizontalLayout_22.addItem(spacerItem17)

        self.button_servo_align3 = QtWidgets.QPushButton(self.widget_24)
        self.button_linear_plan3 = QtWidgets.QPushButton(self.widget_24)
        self.button_close_clampA3 = QtWidgets.QPushButton(self.widget_24)
        self.button_joint4_reverse_3 = QtWidgets.QPushButton(self.widget_24)
        self.log_pos = QtWidgets.QPushButton(self.widget_24)
        for i,btn in enumerate([self.log_pos,self.button_joint4_reverse_3,self.button_servo_align3, self.button_linear_plan3, self.button_close_clampA3]):
                btn.setStyleSheet("background-color: #f4f4f4;\n"
                "color: black;\n"
                "font: 15pt \"Adobe 黑体 Std R\";\n"
                "   \n"
                "margin-left: 60px;"
                #"padding: 5px 10px;\n"
                "\n"
                "border-left:0px;\n"
                "border-top:0px;\n"
                " border-right: 2px solid #a3a3a3;  /* 右边边框 */\n"
                "    border-bottom: 2px solid #a3a3a3; /* 下边边框 */\n"
                "margin-top: 0px;")
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(btn.sizePolicy().hasHeightForWidth())
                btn.setSizePolicy(sizePolicy)
                btn.setMinimumSize(QtCore.QSize(400, 50))

                # ====== 新增：创建 QLabel 并放入水平布局 ======
                label = QtWidgets.QLabel()
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(label.sizePolicy().hasHeightForWidth())
                label.setSizePolicy(sizePolicy)
                label.setMinimumSize(QtCore.QSize(30, 30))
                label.setStyleSheet("background-color: rgb(255, 0, 0);\n"
        "border-radius: 15px; \n"
        "border: 1px solid gray;\n"
        "margin-top: 0px;\n"
        "")
                label.setText("")
                label.setObjectName(f"led{i+21}")

                h_layout = QtWidgets.QHBoxLayout()
                h_layout.addWidget(btn)
                h_layout.addWidget(label)

                self.verticalLayout_22.addLayout(h_layout)
                self.verticalLayout_22.setStretch(i,1)
                setattr(self,f"led{i+21}",label)

        self.log_pos.setObjectName("log_pos")
        self.button_joint4_reverse_3.setObjectName("button_joint4_reverse_3")
        self.button_servo_align3.setObjectName("button_servo_align3")
        self.button_linear_plan3.setObjectName("button_linear_plan3")
        self.button_close_clampA3.setObjectName("button_close_clampA3")

        #self.verticalLayout_12.addWidget(self.widget_24)
        self.widget_28 = QtWidgets.QWidget(self.widget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_28.sizePolicy().hasHeightForWidth())
        self.widget_28.setSizePolicy(sizePolicy)
        self.widget_28.setMinimumSize(QtCore.QSize(0, 45))
        self.widget_28.setStyleSheet("border:none\n"
"")
        self.widget_28.setObjectName("widget_28")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.widget_28)
        self.verticalLayout_26.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_26.setSpacing(5)
        '''self.button4 = QtWidgets.QPushButton(self.widget_28)
        self.button4.setMinimumSize(QtCore.QSize(120, 0))
        self.button4.setStyleSheet("background-color: #f4f4f4;\n"
"color: black;\n"
"   \n"
"padding: 5px 10px;\n"
"\n"
"border-left:0px;\n"
"border-top:0px;\n"
" border-right: 2px solid #a3a3a3;  /* 右边边框 */\n"
"    border-bottom: 2px solid #a3a3a3; /* 下边边框 */\n"
"margin-top: 0px;")
        self.button4.setObjectName("button4")
        self.horizontalLayout_26.addWidget(self.button4)'''
        #spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        #self.horizontalLayout_26.addItem(spacerItem18)
        '''self.led4 = QtWidgets.QLabel(self.widget_28)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.led4.sizePolicy().hasHeightForWidth())
        self.led4.setSizePolicy(sizePolicy)
        self.led4.setMinimumSize(QtCore.QSize(30, 30))
        self.led4.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"border-radius: 15px; \n"
"border: 1px solid gray;\n"
"margin-top: 0px;\n"
"")
        self.led4.setText("")
        self.led4.setObjectName("led4")
        self.horizontalLayout_26.addWidget(self.led4)'''
        #spacerItem19 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        #self.horizontalLayout_26.addItem(spacerItem19)

        self.mounting4 = QtWidgets.QPushButton(self.widget_28)
        self.button_linear_plan4 = QtWidgets.QPushButton(self.widget_28)
        for btn in [self.mounting4,self.button_linear_plan4]:
                btn.setStyleSheet("background-color: #f4f4f4;\n"
                "color: black;\n"
                "font: 15pt \"Adobe 黑体 Std R\";\n"
                "   \n"
                "margin-left: 60px;"
                #"padding: 5px 10px;\n"
                "\n"
                "border-left:0px;\n"
                "border-top:0px;\n"
                " border-right: 2px solid #a3a3a3;  /* 右边边框 */\n"
                "    border-bottom: 2px solid #a3a3a3; /* 下边边框 */\n"
                "margin-top: 0px;")
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(btn.sizePolicy().hasHeightForWidth())
                btn.setSizePolicy(sizePolicy)
                btn.setMinimumSize(QtCore.QSize(400, 50))

                # ====== 新增：创建 QLabel 并放入水平布局 ======
                label = QtWidgets.QLabel()
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(label.sizePolicy().hasHeightForWidth())
                label.setSizePolicy(sizePolicy)
                label.setMinimumSize(QtCore.QSize(30, 30))
                label.setStyleSheet("background-color: rgb(255, 0, 0);\n"
        "border-radius: 15px; \n"
        "border: 1px solid gray;\n"
        "margin-top: 0px;\n"
        "")
                label.setText("")
                label.setObjectName(f"led31")

                h_layout = QtWidgets.QHBoxLayout()
                h_layout.addWidget(btn)
                h_layout.addWidget(label)

                self.verticalLayout_26.addLayout(h_layout)
                self.verticalLayout_26.setStretch(i,1)
                setattr(self,f"led{i+31}",label)

        self.mounting4.setObjectName("mounting4")
        self.button_linear_plan4.setObjectName("button_linear_plan4")

        self.button1 = QtWidgets.QPushButton(self.widget_14)
        self.button1.setMinimumSize(QtCore.QSize(180, 70))
        self.button1.setStyleSheet(
              "font: 15pt \"Adobe 黑体 Std R\";\n"
              "background-color: #f4f4f4;\n"
                "color: black;\n"
                "padding: 10px 10px;\n"
                "border-left:0px;\n"
                "border-top:5px;\n"
                "border-right: 2px solid #a3a3a3;\n"
                "border-bottom: 5px solid #a3a3a3;"
                )
        self.button1.setObjectName("button1")

        self.button2 = QtWidgets.QPushButton(self.widget_14)
        self.button2.setMinimumSize(QtCore.QSize(180, 70))
        self.button2.setStyleSheet(self.button1.styleSheet())
        self.button2.setObjectName("button2")

        self.button3 = QtWidgets.QPushButton(self.widget_14)
        self.button3.setMinimumSize(QtCore.QSize(180, 70))
        self.button3.setStyleSheet(self.button1.styleSheet())
        self.button3.setObjectName("button3")

        self.button4 = QtWidgets.QPushButton(self.widget_14)
        self.button4.setMinimumSize(QtCore.QSize(180, 70))
        self.button4.setStyleSheet(self.button1.styleSheet())
        self.button4.setObjectName("button4")
        # 确保按钮自身允许垂直拉伸
        for btn in [self.button1, self.button2, self.button3, self.button4]:
            btn.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        #self.verticalLayout_12.addWidget(self.widget_28)
        # ========== 3. 设置 widget_14 的布局（水平）==========
        main_layout = QtWidgets.QHBoxLayout(self.widget_14)
        main_layout.setContentsMargins(0, 0, 0, 0)

        # 左侧导航
        nav_layout = QtWidgets.QVBoxLayout()
        nav_layout.setAlignment(QtCore.Qt.AlignTop)
        nav_layout.addWidget(self.button1)
        nav_layout.addWidget(self.button2)
        nav_layout.addWidget(self.button3)
        nav_layout.addWidget(self.button4)

        nav_widget = QtWidgets.QWidget()
        nav_widget.setLayout(nav_layout)
        nav_widget.setFixedWidth(200)

        # 关键：让按钮在垂直方向均匀拉伸（等高并填满空间）
        nav_layout.setStretch(0, 1)  # button1
        nav_layout.setStretch(1, 1)  # button2
        nav_layout.setStretch(2, 1)  # button3
        nav_layout.setStretch(3, 1)  # button4

        # 右侧内容
        self.stacked_widget = QtWidgets.QStackedWidget()
        self.stacked_widget.addWidget(self.widget_22)
        self.stacked_widget.addWidget(self.widget_23)
        self.stacked_widget.addWidget(self.widget_24)
        self.stacked_widget.addWidget(self.widget_28)

        # 连接信号
        self.button1.clicked.connect(lambda: self.switch_page(0))
        self.button2.clicked.connect(lambda: self.switch_page(1))
        self.button3.clicked.connect(lambda: self.switch_page(2))
        self.button4.clicked.connect(lambda: self.switch_page(3))

        # 默认选中
        self.button1.setChecked(True)
        self.stacked_widget.setCurrentIndex(0)

        # 添加到主布局
        main_layout.addWidget(nav_widget)
        main_layout.addWidget(self.stacked_widget)

        self.verticalLayout_16.addWidget(self.widget_14)
        self.verticalLayout_2.addWidget(self.groupBox_5)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupTarget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox_4.setStyleSheet("font: 15pt \"Adobe 黑体 Std R\";\n"
"border-color: rgb(249, 249, 249);\n"
"border: 3px solid #f9f9f9;      /* 边框粗细+颜色 */\n"
"border-radius: 8px;         /* 圆角半径 */\n"
"margin-top: 1ex;\n"
"color:white\n"
"")
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_8.setContentsMargins(-1, 9, -1, 5)
        self.verticalLayout_8.setSpacing(18)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.logText = QtWidgets.QPlainTextEdit(self.groupBox_4)
        self.logText.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logText.sizePolicy().hasHeightForWidth())
        self.logText.setSizePolicy(sizePolicy)
        self.logText.setMinimumSize(QtCore.QSize(800, 60))
        self.logText.setMaximumSize(QtCore.QSize(800, 1000))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.logText.setFont(font)
        self.logText.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 14pt \"Adobe 黑体 Std R\" ;\n"
"color: black;")
        self.logText.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.logText.setReadOnly(True)
        self.logText.setBackgroundVisible(False)
        self.logText.setCenterOnScroll(False)
        self.logText.setObjectName("logText")
        self.verticalLayout_8.addWidget(self.logText)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.horizontalLayout_5.addWidget(self.groupTarget)
        self.groupMonitor = QtWidgets.QGroupBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupMonitor.sizePolicy().hasHeightForWidth())
        self.groupMonitor.setSizePolicy(sizePolicy)
        self.groupMonitor.setMinimumSize(QtCore.QSize(680, 0))
        self.groupMonitor.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupMonitor.setFont(font)
        self.groupMonitor.setStyleSheet("")
        self.groupMonitor.setTitle("")
        self.groupMonitor.setObjectName("groupMonitor")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupMonitor)
        self.verticalLayout.setContentsMargins(20, -1, -1, 4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupMonitor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 375))
        self.groupBox_3.setStyleSheet("font: 15pt \"Adobe 黑体 Std R\";\n"
"border-color: rgb(249, 249, 249);\n"
"border: 3px solid #f9f9f9;      /* 边框粗细+颜色 */\n"
"border-radius: 8px;         /* 圆角半径 */\n"
"margin-top: 1ex;\n"
"color:white\n"
"")
        self.groupBox_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.VisionPictureRGB_2 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VisionPictureRGB_2.sizePolicy().hasHeightForWidth())
        self.VisionPictureRGB_2.setSizePolicy(sizePolicy)
        self.VisionPictureRGB_2.setMinimumSize(QtCore.QSize(467, 336))
        self.VisionPictureRGB_2.setStyleSheet("border-radius: 0px; \n"
"border:none;\n"
"background-color: rgb(255, 255, 255);")
        self.VisionPictureRGB_2.setText("")
        self.VisionPictureRGB_2.setAlignment(QtCore.Qt.AlignCenter)
        self.VisionPictureRGB_2.setObjectName("VisionPictureRGB_2")
        self.horizontalLayout_7.addWidget(self.VisionPictureRGB_2)
        self.widget_4 = QtWidgets.QWidget(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setMinimumSize(QtCore.QSize(400, 0))
        self.widget_4.setStyleSheet("border-color: rgb(173, 178, 181);\n"
"background-color:#d3d3d3;\n"
"border-radius: 0px; \n"
"color:black;\n"
"font: 14pt \"Adobe 黑体 Std R\";\n"
"")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_10 = QtWidgets.QWidget(self.widget_4)
        self.widget_10.setStyleSheet("border:none\n"
"")
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_7.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label = QtWidgets.QLabel(self.widget_10)
        self.label.setObjectName("label")
        self.verticalLayout_7.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget_10)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_7.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget_10)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.widget_10)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)
        self.label_6 = QtWidgets.QLabel(self.widget_10)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6)
        self.label_32 = QtWidgets.QLabel(self.widget_10)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_7.addWidget(self.label_32)
        self.horizontalLayout.addWidget(self.widget_10)
        self.widget_19 = QtWidgets.QWidget(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_19.sizePolicy().hasHeightForWidth())
        self.widget_19.setSizePolicy(sizePolicy)
        self.widget_19.setStyleSheet("border:none\n"
"")
        self.widget_19.setObjectName("widget_19")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.widget_19)
        self.verticalLayout_20.setContentsMargins(0, 7, 0, 0)
        self.verticalLayout_20.setSpacing(7)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.line_x = QtWidgets.QLineEdit(self.widget_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_x.sizePolicy().hasHeightForWidth())
        self.line_x.setSizePolicy(sizePolicy)
        self.line_x.setMinimumSize(QtCore.QSize(100, 0))
        self.line_x.setStyleSheet("background-color: #f9f9f9;\n"
"padding: 5px 10px;\n"
"border:none;\n"
"margin-top: 0px;")
        self.line_x.setObjectName("line_x")
        self.verticalLayout_20.addWidget(self.line_x)
        self.line_y = QtWidgets.QLineEdit(self.widget_19)
        self.line_y.setStyleSheet("background-color: #f9f9f9;\n"
"padding: 5px 10px;\n"
"border:none;\n"
"margin-top: 0px;")
        self.line_y.setObjectName("line_y")
        self.verticalLayout_20.addWidget(self.line_y)
        self.line_z = QtWidgets.QLineEdit(self.widget_19)
        self.line_z.setStyleSheet("background-color: #f9f9f9;\n"
"padding: 5px 10px;\n"
"border:none;\n"
"margin-top: 0px;")
        self.line_z.setObjectName("line_z")
        self.verticalLayout_20.addWidget(self.line_z)
        self.line_Rx = QtWidgets.QLineEdit(self.widget_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_Rx.sizePolicy().hasHeightForWidth())
        self.line_Rx.setSizePolicy(sizePolicy)
        self.line_Rx.setStyleSheet("background-color: #f9f9f9;\n"
"padding: 5px 10px;\n"
"border:none;\n"
"margin-top: 0px;")
        self.line_Rx.setObjectName("line_Rx")
        self.verticalLayout_20.addWidget(self.line_Rx)
        self.line_Ry = QtWidgets.QLineEdit(self.widget_19)
        self.line_Ry.setStyleSheet("background-color: #f9f9f9;\n"
"padding: 5px 10px;\n"
"border:none;\n"
"margin-top: 0px;")
        self.line_Ry.setObjectName("line_Ry")
        self.verticalLayout_20.addWidget(self.line_Ry)
        self.line_Rz = QtWidgets.QLineEdit(self.widget_19)
        self.line_Rz.setStyleSheet("background-color: #f9f9f9;\n"
"padding: 5px 10px;\n"
"border:none;\n"
"margin-top: 0px;")
        self.line_Rz.setObjectName("line_Rz")
        self.verticalLayout_20.addWidget(self.line_Rz)
        self.horizontalLayout.addWidget(self.widget_19)
        self.widget_12 = QtWidgets.QWidget(self.widget_4)
        self.widget_12.setStyleSheet("border:none\n"
"")
        self.widget_12.setObjectName("widget_12")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.widget_12)
        self.verticalLayout_17.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_37 = QtWidgets.QLabel(self.widget_12)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_17.addWidget(self.label_37)
        self.label_38 = QtWidgets.QLabel(self.widget_12)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_17.addWidget(self.label_38)
        self.label_39 = QtWidgets.QLabel(self.widget_12)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_17.addWidget(self.label_39)
        self.label_40 = QtWidgets.QLabel(self.widget_12)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_17.addWidget(self.label_40)
        self.label_41 = QtWidgets.QLabel(self.widget_12)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_17.addWidget(self.label_41)
        self.label_33 = QtWidgets.QLabel(self.widget_12)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_17.addWidget(self.label_33)
        self.horizontalLayout.addWidget(self.widget_12)
        self.widget_18 = QtWidgets.QWidget(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_18.sizePolicy().hasHeightForWidth())
        self.widget_18.setSizePolicy(sizePolicy)
        self.widget_18.setStyleSheet("border:none\n"
"")
        self.widget_18.setObjectName("widget_18")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.widget_18)
        self.verticalLayout_19.setContentsMargins(0, 7, 0, 0)
        self.verticalLayout_19.setSpacing(7)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.line_Fx = QtWidgets.QLineEdit(self.widget_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_Fx.sizePolicy().hasHeightForWidth())
        self.line_Fx.setSizePolicy(sizePolicy)
        self.line_Fx.setMinimumSize(QtCore.QSize(100, 0))
        self.line_Fx.setStyleSheet("background-color: #f9f9f9;\n"
"padding: 5px 10px;\n"
"border:none;\n"
"margin-top: 0px;")
        self.line_Fx.setObjectName("line_Fx")
        self.verticalLayout_19.addWidget(self.line_Fx)
        self.line_Fy = QtWidgets.QLineEdit(self.widget_18)
        self.line_Fy.setStyleSheet("background-color: #f9f9f9;\n"
"padding: 5px 10px;\n"
"border:none;\n"
"margin-top: 0px;")
        self.line_Fy.setObjectName("line_Fy")
        self.verticalLayout_19.addWidget(self.line_Fy)
        self.line_Fz = QtWidgets.QLineEdit(self.widget_18)
        self.line_Fz.setStyleSheet("background-color: #f9f9f9;\n"
"padding: 5px 10px;\n"
"border:none;\n"
"margin-top: 0px;")
        self.line_Fz.setObjectName("line_Fz")
        self.verticalLayout_19.addWidget(self.line_Fz)
        self.line_Tx = QtWidgets.QLineEdit(self.widget_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_Tx.sizePolicy().hasHeightForWidth())
        self.line_Tx.setSizePolicy(sizePolicy)
        self.line_Tx.setStyleSheet("background-color: #f9f9f9;\n"
"padding: 5px 10px;\n"
"border:none;\n"
"margin-top: 0px;")
        self.line_Tx.setObjectName("line_Tx")
        self.verticalLayout_19.addWidget(self.line_Tx)
        self.line_Ty = QtWidgets.QLineEdit(self.widget_18)
        self.line_Ty.setStyleSheet("background-color: #f9f9f9;\n"
"padding: 5px 10px;\n"
"border:none;\n"
"margin-top: 0px;")
        self.line_Ty.setObjectName("line_Ty")
        self.verticalLayout_19.addWidget(self.line_Ty)
        self.line_Tz = QtWidgets.QLineEdit(self.widget_18)
        self.line_Tz.setStyleSheet("background-color: #f9f9f9;\n"
"padding: 5px 10px;\n"
"border:none;\n"
"margin-top: 0px;")
        self.line_Tz.setObjectName("line_Tz")
        self.verticalLayout_19.addWidget(self.line_Tz)
        self.horizontalLayout.addWidget(self.widget_18)
        self.horizontalLayout_7.addWidget(self.widget_4)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_31 = QtWidgets.QGroupBox(self.groupMonitor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_31.sizePolicy().hasHeightForWidth())
        self.groupBox_31.setSizePolicy(sizePolicy)
        self.groupBox_31.setStyleSheet("font: 15pt \"Adobe 黑体 Std R\";\n"
"border-color: rgb(249, 249, 249);\n"
"border: 3px solid #f9f9f9;      /* 边框粗细+颜色 */\n"
"border-radius: 8px;         /* 圆角半径 */\n"
"margin-top: 1ex;\n"
"color:white\n"
"")
        self.groupBox_31.setObjectName("groupBox_31")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_31)
        self.verticalLayout_3.setContentsMargins(-1, 25, -1, 20)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.table = QtWidgets.QTableWidget(self.groupBox_31)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table.sizePolicy().hasHeightForWidth())
        self.table.setSizePolicy(sizePolicy)
        self.table.setMinimumSize(QtCore.QSize(0, 25))
        self.table.setStyleSheet("alternate-background-color: rgb(255, 255, 255);\n"
"\n"
"background-color: rgb(241, 241, 241);\n"
"\n"
"border-radius: 0px; \n"
"color:black;\n"
"font: 14pt \"Adobe 黑体 Std R\";\n"
"\n"
"margin-top: 0ex;\n"
"border: 0px ;      /* 边框粗细+颜色 */")
        self.table.setInputMethodHints(QtCore.Qt.ImhNone)
        self.table.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.table.setFrameShadow(QtWidgets.QFrame.Raised)
        self.table.setLineWidth(100)
        self.table.setMidLineWidth(100)
        self.table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.table.setAutoScroll(True)
        self.table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table.setDragEnabled(False)
        self.table.setAlternatingRowColors(True)
        self.table.setGridStyle(QtCore.Qt.DashLine)
        self.table.setRowCount(9)
        self.table.setObjectName("table")
        self.table.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(55, 55, 55, 22))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setText("电机状态")
        item.setBackground(QtGui.QColor(255, 255, 0, 54))
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.table.setHorizontalHeaderItem(4, item)
        self.table.horizontalHeader().setVisible(True)
        self.table.horizontalHeader().setCascadingSectionResizes(False)
        self.table.horizontalHeader().setDefaultSectionSize(150)
        self.table.horizontalHeader().setHighlightSections(False)
        self.table.horizontalHeader().setMinimumSectionSize(33)
        self.table.horizontalHeader().setSortIndicatorShown(False)
        self.table.horizontalHeader().setStretchLastSection(True)
        self.table.verticalHeader().setVisible(True)
        self.table.verticalHeader().setCascadingSectionResizes(False)
        self.table.verticalHeader().setDefaultSectionSize(44)
        self.table.verticalHeader().setHighlightSections(False)
        self.table.verticalHeader().setMinimumSectionSize(39)
        self.table.verticalHeader().setSortIndicatorShown(False)
        self.table.verticalHeader().setStretchLastSection(True)
        self.verticalLayout_3.addWidget(self.table)
        self.verticalLayout.addWidget(self.groupBox_31)
        self.horizontalLayout_5.addWidget(self.groupMonitor)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.verticalLayout_5.setStretch(0, 1)
        self.gridLayout_6.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "空间碎片抓捕地面实验系统"))
        self.label_5.setText(_translate("MainWindow", "空 间 爬 行 臂 装 配 实 验 系 统"))
        self.SingleMachine.setTitle(_translate("MainWindow", "总体控制"))
        self.button_connect.setText(_translate("MainWindow", "启动"))
        self.button_motor.setText(_translate("MainWindow", "开启电机"))
        self.button_switch.setText(_translate("MainWindow", "开启/切换"))
        self.SingleMachine_2.setTitle(_translate("MainWindow", "单机调试"))
        self.button_start.setText(_translate("MainWindow", "启动"))
        self.button_forward.setText(_translate("MainWindow", "正转"))
        self.button_reverse.setText(_translate("MainWindow", "反转"))
        self.label_43.setText(_translate("MainWindow", "位置"))
        self.button_stop.setText(_translate("MainWindow", "停止"))
        self.button_reset.setText(_translate("MainWindow", "复位"))
        self.button_zero.setText(_translate("MainWindow", "回零"))
        self.button_move.setText(_translate("MainWindow", "移动"))
        self.label_44.setText(_translate("MainWindow", "速度"))
        self.groupBox_5.setTitle(_translate("MainWindow", "分系统流程"))
        self.button1.setText(_translate("MainWindow", "第一步爬行"))
        self.button2.setText(_translate("MainWindow", "第二步爬行"))
        self.button3.setText(_translate("MainWindow", "第三步爬行"))
        self.button4.setText(_translate("MainWindow", "装配"))

        self.button_servo_align1.setText(_translate("MainWindow", "伺服对齐"))
        self.button_linear_plan1.setText(_translate("MainWindow", "直线规划"))
        self.button_close_clampA1.setText(_translate("MainWindow", "闭合末端夹爪"))
        self.button_release_clampB1.setText(_translate("MainWindow", "松开基座夹爪"))
        self.button_reverse_linear_1.setText(_translate("MainWindow", "反向直线规划"))
        self.button_joint4_reverse_1.setText(_translate("MainWindow", "反转关节4"))

        self.button_servo_align2.setText(_translate("MainWindow", "伺服对齐"))
        self.button_linear_plan2.setText(_translate("MainWindow", "直线规划"))
        self.button_close_clampA2.setText(_translate("MainWindow", "闭合末端夹爪"))
        self.button_release_clampB2.setText(_translate("MainWindow", "松开基座夹爪"))
        self.button_reverse_linear_2.setText(_translate("MainWindow", "反向直线规划"))
        self.button_joint4_reverse_2.setText(_translate("MainWindow", "反转关节4"))

        self.log_pos.setText(_translate("MainWindow", "记录位置"))
        self.button_joint4_reverse_3.setText(_translate("MainWindow", "反转关节4"))
        self.button_servo_align3.setText(_translate("MainWindow", "伺服对齐"))
        self.button_linear_plan3.setText(_translate("MainWindow", "直线规划"))
        self.button_close_clampA3.setText(_translate("MainWindow", "闭合末端夹爪"))

        self.mounting4.setText(_translate("MainWindow", "移动到装配位置正前方"))
        self.button_linear_plan4.setText(_translate("MainWindow", "直线规划"))

        self.groupBox_4.setTitle(_translate("MainWindow", "日志"))
        self.groupBox_3.setTitle(_translate("MainWindow", "数据监控"))
        self.label.setText(_translate("MainWindow", "X"))
        self.label_2.setText(_translate("MainWindow", "Y"))
        self.label_3.setText(_translate("MainWindow", "Z"))
        self.label_4.setText(_translate("MainWindow", "Rx"))
        self.label_6.setText(_translate("MainWindow", "Ry"))
        self.label_32.setText(_translate("MainWindow", "Rz"))
        self.label_37.setText(_translate("MainWindow", "Fx"))
        self.label_38.setText(_translate("MainWindow", "Fy"))
        self.label_39.setText(_translate("MainWindow", "Fz"))
        self.label_40.setText(_translate("MainWindow", "Tx"))
        self.label_41.setText(_translate("MainWindow", "Ty"))
        self.label_33.setText(_translate("MainWindow", "Tz"))
        self.groupBox_31.setTitle(_translate("MainWindow", "电机"))
        self.table.setSortingEnabled(False)
        item = self.table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "手爪电机1"))
        item = self.table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "关节电机1"))
        item = self.table.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "关节电机2"))
        item = self.table.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "关节电机3"))
        item = self.table.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "关节电机4"))
        item = self.table.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "关节电机5"))
        item = self.table.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "关节电机6"))
        item = self.table.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "关节电机7"))
        item = self.table.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "手爪电机2"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "电机编号"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "电机转速"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "当前位置"))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "报警号"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))

    # ====== 添加切换方法（放在你的类中）======
    def switch_page(self, index):
        self.stacked_widget.setCurrentIndex(index)